version: "3.9"
services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cantaoria_web
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__ConnectionString=Server=sqlserver;Database=Cantaoria;Integrated Security=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ""
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
